# Generated by Django 5.0.4 on 2026-08-04 19:39

from django.conf import settings
from django.db import migrations
import os
import shutil

from api.utils import FilesUtils


def copy_default_icons_to_media(apps, schema_editor):
    """Copy the default station type icons (shipped in assets/) to the media folder.

    Icons used to be searched on assets/ for the station types created at start up
    (search_icon_on_assets_folder flag, removed by this migration) and on media/ for
    the rest. Now every icon is resolved against MEDIA_ROOT, so the default ones have
    to live there too.

    Copies by folder instead of by station type because on a fresh database the icon
    names are set by migrations 0022 / 0024, which may run before the types exist.
    """
    src_dir = os.path.join(settings.ASSETS_FOLDER, 'station_type_icons')
    dst_dir = os.path.join(settings.MEDIA_ROOT, 'station_type_icons')

    if not os.path.isdir(src_dir):
        return

    os.makedirs(dst_dir, exist_ok=True)

    for filename in os.listdir(src_dir):
        src = os.path.join(src_dir, filename)
        dst = os.path.join(dst_dir, filename)

        if not os.path.isfile(src) or os.path.exists(dst):
            # don't overwrite an icon already uploaded with the same name
            continue

        shutil.copy2(src, dst)
        # migrations run as root on the entrypoint, media is a mounted volume
        FilesUtils.set_file_ownership(
            dst, settings.USER_ID_TO_SAVE_FILES, settings.GROUP_ID_TO_SAVE_FILES)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_register_distinct_codes_endpoints'),
    ]

    operations = [
        migrations.RunPython(copy_default_icons_to_media,
                             migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='stationtype',
            name='search_icon_on_assets_folder',
        ),
    ]
