# Generated by Django 5.0.4 on 2026-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_stations_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='planned',
            field=models.BooleanField(default=False),
        ),
    ]
