# Generated by Django 5.0.4 on 2026-08-14

from django.db import migrations


def create_endpoint(apps, schema_editor):
    Endpoint = apps.get_model("api", "Endpoint")

    Endpoint.objects.get_or_create(path="/api/update-planned-visits-status", method="POST")

    Resource = apps.get_model("api", "Resource")

    Resource.objects.get_or_create(name="planned-visits-status")

    endpoints_cluster = apps.get_model("api", "EndPointsCluster")
    endpoint = apps.get_model("api", "Endpoint")
    cluster_type = apps.get_model("api", "ClusterType")
    resource = apps.get_model("api", "Resource")

    front_read_stations = endpoints_cluster(resource=resource.objects.get(name='planned-visits-status'),
                                            cluster_type=cluster_type.objects.get(name="read-write"), role_type='API')

    front_read_stations.save()

    front_read_stations.endpoints.add(
        endpoint.objects.get(path="/api/update-planned-visits-status", method="POST"))


def allow_update_gaps_user_to_update_planned_visits(apps, schema_editor):

    Role = apps.get_model("api", "Role")
    EndPointsCluster = apps.get_model("api", "EndPointsCluster")
    cluster_type = apps.get_model("api", "ClusterType")
    resource = apps.get_model("api", "Resource")

    update_gaps_status_role = Role.objects.get(
        name="update-gaps-status")

    update_gaps_status_role.endpoints_clusters.add(EndPointsCluster.objects.get(resource=resource.objects.get(name='planned-visits-status'),
                                                                             cluster_type=cluster_type.objects.get(name="read-write"), role_type='API'))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_visits_planned'),
    ]

    operations = [
        migrations.RunPython(
            create_endpoint
        ),
        migrations.RunPython(
            allow_update_gaps_user_to_update_planned_visits
        ),
    ]
