# Generated by Django 5.0.4 on 2026-08-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_register_transfer_visits_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcesMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol', models.CharField()),
                ('fqdn', models.CharField()),
                ('username', models.CharField(blank=True, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('path', models.CharField(blank=True, null=True)),
                ('format', models.ForeignKey(blank=True, db_column='format', null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='api.sourcesformats', to_field='format')),
            ],
            options={
                'db_table': 'sources_metadata',
                'ordering': ['fqdn'],
                'managed': False,
            },
        ),
        # makemigrations does not detect field changes on managed=False models: added by hand
        migrations.AddField(
            model_name='sourcesservers',
            name='metadata_source_id',
            field=models.ForeignKey(blank=True, db_column='metadata_source_id', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='api.sourcesmetadata'),
        ),
    ]
