# Generated by Django 5.0.4 on 2026-09-03 15:30

import django.contrib.postgres.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_endpoints_clusters_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamitProjects',
            fields=[
                ('project', models.CharField(max_length=20, unique=True)),
                ('network_type', models.CharField(choices=[('regional', 'regional'), ('global', 'global')], default='global', max_length=20)),
                ('cluster_size', models.IntegerField(default=25)),
                ('ties', models.IntegerField(default=10)),
                ('process_defaults', models.TextField(blank=True, null=True)),
                ('sestbl', models.TextField(blank=True, null=True)),
                ('solutions_dir', models.TextField(blank=True, null=True)),
                ('experiment_type', models.CharField(choices=[('baseline', 'baseline'), ('relax', 'relax'), ('orbit', 'orbit')], default='baseline', max_length=20)),
                ('experiment_name', models.CharField(blank=True, max_length=4, null=True)),
                ('org', models.CharField(blank=True, max_length=3, null=True)),
                ('noftp', models.BooleanField(default=True)),
                ('eop_type', models.CharField(default='usno', max_length=10)),
                ('systems', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('G', 'GPS'), ('R', 'GLONASS'), ('E', 'Galileo'), ('C', 'BeiDou')], max_length=1), blank=True, null=True, size=None)),
                ('overconst_action', models.CharField(blank=True, choices=[('inflate', 'inflate'), ('relax', 'relax'), ('remove', 'remove'), ('delete', 'delete')], max_length=10, null=True)),
                ('sigma_floor_h', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=6)),
                ('sigma_floor_v', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), max_digits=6)),
                ('station_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, null=True, size=None)),
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gamit_projects',
                'ordering': ['project'],
                'managed': False,
            },
        ),
    ]
