# Generated by Django 5.0.4 on 2026-09-08 12:18

import datetime
import django.contrib.postgres.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_register_gamit_projects_endpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_city', models.CharField(max_length=255)),
                ('end_city', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('stations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('new_sites', models.JSONField(blank=True, default=list)),
                ('time_on_site_minutes', models.IntegerField(default=120)),
                ('station_time_overrides', models.JSONField(blank=True, default=dict)),
                ('fuel_cost_per_km', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('lodging_cost_per_night', models.DecimalField(decimal_places=2, default=Decimal('70'), max_digits=10)),
                ('per_diem_cost_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('num_participants', models.IntegerField(default=1)),
                ('day_start', models.TimeField(default=datetime.time(8, 0))),
                ('hard_stop', models.TimeField(default=datetime.time(20, 0))),
            ],
            options={
                'db_table': 'campaign_plans',
                'ordering': ['-start_date'],
            },
        ),
    ]
